# Lorax Core Package - Cloud Build CI/CD Pipeline
#
# Publishes @lorax/core to npm registry on version tags.
#
# Trigger: Git tag matching pattern: core-v*
#   Example: core-v1.0.0, core-v1.2.3
#
# Required secrets (set in Secret Manager):
#   - npm-token: NPM authentication token with publish permissions
#
# Setup trigger:
#   gcloud builds triggers create github \
#     --repo-name=lorax \
#     --repo-owner=YOUR_ORG \
#     --tag-pattern="^core-v.*" \
#     --build-config=cloudbuild-core.yaml

steps:
  # Step 1: Install dependencies
  - name: 'node:22'
    id: 'install'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd packages/core
        npm install

  # Step 2: Run tests (if available)
  - name: 'node:22'
    id: 'test'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd packages/core
        if npm run test --if-present 2>/dev/null; then
          echo "Tests passed"
        else
          echo "No tests configured, skipping"
        fi
    waitFor: ['install']

  # Step 3: Extract version from tag and update package.json
  - name: 'node:22'
    id: 'version'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd packages/core
        # Extract version from tag (e.g., core-v1.0.0 -> 1.0.0)
        VERSION=$(echo $TAG_NAME | sed 's/^core-v//')
        echo "Publishing version: $VERSION"
        npm version $VERSION --no-git-tag-version --allow-same-version
    waitFor: ['test']

  # Step 4: Publish to npm
  - name: 'node:22'
    id: 'publish'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        cd packages/core
        echo "//registry.npmjs.org/:_authToken=$$NPM_TOKEN" > ~/.npmrc
        npm publish --access public
        echo "Published @lorax/core successfully"
    secretEnv: ['NPM_TOKEN']
    waitFor: ['version']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/npm-token/versions/latest
      env: 'NPM_TOKEN'

options:
  logging: CLOUD_LOGGING_ONLY
