name: Build Lorax Frontend

on:
  push:
    branches: [ main ]
    paths: [ "frontend/**" ]
  pull_request:
    paths: [ "frontend/**" ]
  workflow_dispatch: {}   # allow manual runs from the Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: yarn
          cache-dependency-path: frontend/yarn.lock

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: vite-dist
          path: frontend/dist
